######################################################################
# Automatically generated by qmake (3.0) ?? ?? 6 21:02:36 2013
######################################################################

TEMPLATE = app
TARGET = ODE
INCLUDEPATH += .

# Input
HEADERS += ODE/ode.h
FORMS += ODE/ode.ui
SOURCES += ODE/main.cpp ODE/ode.cpp
RESOURCES += ODE/ode.qrc
LIBS += glut.lib glut32.lib